.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. merica_qt test_merica_qt
clean: FORCE
	$(MAKE) -C .. merica_qt_clean test_merica_qt_clean
check: FORCE
	$(MAKE) -C .. test_merica_qt_check
merica-qt merica-qt.exe: FORCE
	 $(MAKE) -C .. merica_qt
